
<html>
  <head>
    <title>Lab 04 - Graded Solution</title>
  </head>
  <body>
    <h1>Lab 04 - Graded Solution</h1>
    <p><b>You scored 0% = 0.0 points for this lab.</b></p>
    <ul>
      <li><b>Testing subscript-based acess</b>
      <ul>
      <li>Grade Percentage: 15</li>
      <li>Your solution failed this test case! taking 0.304 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
      <li><b>test stringification</b>
      <ul>
      <li>Grade Percentage: 10</li>
      <li>Your solution failed this test case! taking 0.301 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
      <li><b>testing single-element manipulation</b>
      <ul>
      <li>Grade Percentage: 15</li>
      <li>Your solution failed this test case! taking 0.308 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
      <li><b>testing predicates</b>
      <ul>
      <li>Grade Percentage: 15</li>
      <li>Your solution failed this test case! taking 0.308 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
      <li><b>testing queries</b>
      <ul>
      <li>Grade Percentage: 15</li>
      <li>Your solution failed this test case! taking 0.323 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
      <li><b>testing bulk operations</b>
      <ul>
      <li>Grade Percentage: 15</li>
      <li>Your solution failed this test case! taking 0.306 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
      <li><b>testing iteration</b>
      <ul>
      <li>Grade Percentage: 15</li>
      <li>Your solution failed this test case! taking 0.296 sec</Li>
<li><pre>IndentationError: unexpected indent (<tested-program>, line 256)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 256
    max = self.data[0]
IndentationError: unexpected indent
</pre></li>
      </ul>
      </li>
    </ul>
  </body>
</html>
